Cool Co Fridge Management/Models/Fridge_Stock.cs
using System;
using System.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cool_Co_Fridge_Management.Models
{
    public class Fridge_Stock
    {
        [Key]
        public int StockID { get; set; }
        [Required]
        public string ItemName { get; set; }
        [Required]
        public int FridgeTypeID { get; set; } /*foreign key from FridgeType table*/
        [ForeignKey("FridgeTypeID")]
        public Fridge_Type Fridge_Type { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public bool Availability { get; set; } 
    }
}

Cool Co Fridge Management/Controllers/StockControllerController.cs
using Cool_Co_Fridge_Management.Data;
using Cool_Co_Fridge_Management.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Cool_Co_Fridge_Management.Attributes;


namespace Cool_Co_Fridge_Management.Controllers
{
    //[RoleAuthorize("Stock Controller")]

    public class StockControllerController : Controller
    {
        private readonly ApplicationDbContext _context;
        public StockControllerController(ApplicationDbContext dbContext)
        {
            _context= dbContext;
        }
        public IActionResult StockControllerIndex()
        {
            return View();
        }
        public IActionResult Fridge_Stock() /*this is the list*/
        {
            var stocklist = _context.stock
                .Include(s => s.Fridge_Type)
                .ToList();
            return View(stocklist);
        }
        public IActionResult Update_Items() /*Add items*/
        {
            ViewBag.FridgeTypes = new SelectList(_context.fridge_type, "FridgeTypeID", "FridgeType");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update_Items(Fridge_Stock stock)
        {
            _context.stock.Add(stock);
            _context.SaveChanges();
            ViewBag.FridgeTpyes = new SelectList(_context.fridge_type, "FridgeTypeID", "FridgeType");
            return View(stock);
            //return RedirectToAction("Fridge_Stock");
            //if (ModelState.IsValid)
            //{
                
            //}
            //ViewBag.FridgeTypes = new SelectList(_context.fridge_type, "FridgeTypeID", "FridgeType");
            //return View(stock);
        }
        public IActionResult LowStock() /*Should be linked w Customer service*/
        {
            return View();
        }

        public IActionResult CreatePurchaseRequest() 
        {
            return View();
        }

        public IActionResult PurchaseRequestList()/*might be linked with PM*/
        {
            return View();
        }
    }
}

Cool Co Fridge Management/Views/StockController/Fridge_Stock.cshtml
@model IEnumerable<Cool_Co_Fridge_Management.Models.Fridge_Stock>
@{
    ViewData["Title"] = "Fridge_Stock";
}

 
 <div class="container-p3">
     <div class="row pt-4"> 
         <div class="col-6">
             <h2>Stock List</h2>
         </div>
         <div class="col-6 text-right">
            <form asp-controller="StockController" asp-action="Update_Items" method="get" style="display:inline;">
                <button type="submit" class="btn btn-primary">Add items</button>
            </form>

            <form asp-controller="FridgeAllocations" asp-action="AllocatedFridges" method="get" style="display:inline;">
                <button type="submit" class="btn btn-primary">Allocated Fridges</button>
            </form>
         </div>
     </div>
    <br />

    @if (Model != null && Model.Any()) @* (Model.Count() > 0) *@
    {
        <table>
            <thead>
                <tr>
                    <th>ItemName</th>
                    <th>Fridge Type</th>
                    <th>Quantity</th>
                    <th>Availability</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var stock in Model)
                {
                    <tr>
                        <td width="30%">@stock.ItemName</td>
                        <td width="30%">@stock.Fridge_Type.FridgeType</td>
                        <td width="30%">@stock.Quantity</td>
                        <td width="30%">@stock.Availability</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> no records</p>
    }
 </div>

Cool Co Fridge Management/Views/StockController/Update_Items.cshtml
@model Cool_Co_Fridge_Management.Models.Fridge_Stock

<form method="post" asp-action="Update_Items">
    <div class="form-group">
        <label asp-for="ItemName">Item Name</label>
        <input asp-for="ItemName" type="text" class="form-control" required/>
    </div>
    <div class="form-group">
        <label asp-for="FridgeTypeID" class="control-label">Fridge Type</label>
        <select asp-for="FridgeTypeID" class="form-control" asp-items="@(ViewBag.FridgeTypes)">
            <option value="">Select a fridge type</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Quantity">Quantity</label>
        <input asp-for="Quantity"type="number" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Availability">Availability</label>
        <input asp-for="Availability" type="checkbox" class="form-check-input" />
    </div>

    <button type="submit" class="btn btn-primary">Add Item</button>
    <div>
        <a asp-action="Fridge_Stock">Back</a>
    </div>
   
</form>