Cool Co Fridge Management/Models/FridgeFault.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cool_Co_Fridge_Management.Models
{
	public class FridgeFault
	{
		[Key]
		public int FridgeFaultID { get; set; }

		[Display(Name = "FAULT TYPE")]
		public int FaultTypeID { get; set; }
		[ForeignKey("FaultTypeID")]

		[Display(Name = "FAULT TYPE")]
		public FaultType faultType { get; set; }

		[Display(Name = "REPORTED ON")]
		public DateTime? ReportedOn { get; set; }

		public int StatusID { get; set; }
		[ForeignKey("StatusID")]

		[Display(Name = "STATUS")]
		public Status status { get; set; }

		[Display(Name = "REPAIR SCHEDULED FOR")]
		public DateOnly? RepairDate { get; set; }

        [Display(Name = "CONDITION")]
        public int? ConditionID { get; set; }

		[ForeignKey("ConditionID")]
		[Display(Name = "CONDITION")]
		public FridgeCondition? Condition { get; set; }

        public int? UserID { get; set; }
        [ForeignKey("UserID")]

        [Display(Name = "STATUS")]
        public Users? Users { get; set; }
    }
}

Cool Co Fridge Management/Controllers/FridgeFaultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cool_Co_Fridge_Management.Data;
using Cool_Co_Fridge_Management.Models;

namespace Cool_Co_Fridge_Management.Controllers
{
    public class FridgeFaultsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FridgeFaultsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FridgeFaults
        public async Task<IActionResult> Index()
        {
            var pendingStatus = await _context.statuses
				.Where(y => y.StatusDesc == "Pending").FirstOrDefaultAsync();

			var applicationDbContext = _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
				.Where(f => f.StatusID == pendingStatus!.StatusID);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> AcceptedFaults()
        {
            var approveStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Accepted").FirstOrDefaultAsync();

            var applicationDbContext = _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .Where(f => f.StatusID == approveStatus!.StatusID);

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> RejectedFaults()
        {
            var rejectedStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Rejected").FirstOrDefaultAsync();

            var applicationDbContext = _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .Where(f => f.StatusID == rejectedStatus!.StatusID);

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> ScheduleRepairIndex()
        {
            var approveStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Accepted").FirstOrDefaultAsync();

            var applicationDbContext = _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .Where(f => f.StatusID == approveStatus!.StatusID)
                .OrderBy(r => r.RepairDate);

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> ApproveFaultIndex()
        {
			var pendingStatus = await _context.statuses
				.Where(y => y.StatusDesc == "Pending").FirstOrDefaultAsync();

			var applicationDbContext = _context.fridgeFaults
				.Include(f => f.faultType)
				.Include(f => f.status)
				.Where(f => f.StatusID == pendingStatus!.StatusID);
			return View(await applicationDbContext.ToListAsync());
		}

        // GET: FridgeFaults/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);
            if (fridgeFault == null)
            {
                return NotFound();
            }

            return View(fridgeFault);
        }

        // GET: FridgeFaults/Create
        public IActionResult Create()
        {
            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Pending"), "StatusID", "StatusDesc");
            return View();
        }

        // POST: FridgeFaults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FridgeFault fridgeFault)
        {
			fridgeFault.ReportedOn = DateTime.Now;
			var pendingStatus = await _context.statuses
				.Where(y => y.StatusDesc == "Pending").FirstOrDefaultAsync();

			fridgeFault.StatusID = pendingStatus.StatusID;

            //if (ModelState.IsValid)
            //{
            _context.Add(fridgeFault);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc", fridgeFault.FaultTypeID);
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Pending"), "StatusID", "StatusDesc", fridgeFault.StatusID);
            return View(fridgeFault);
        }

        [HttpGet]
        public async Task<IActionResult> ApproveFault(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);
            if (fridgeFault == null)
            {
                return NotFound();
            }

            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Pending"), "StatusID", "StatusDesc");

            return View(fridgeFault);
        }

        [HttpPost]
        public async Task<IActionResult> ApproveFault(int? id, FridgeFault fault)
        {
            var approveStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Accepted").FirstOrDefaultAsync();

            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);

            if (fridgeFault == null)
            {
                return NotFound();
            }

            fridgeFault.StatusID = approveStatus.StatusID;

            _context.Update(fridgeFault);
            await _context.SaveChangesAsync();

            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Accepted"), "StatusID", "StatusDesc");

            return RedirectToAction(nameof(ApproveFaultIndex));
        }

        [HttpGet]
        public async Task<IActionResult> RejectFault(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);
            if (fridgeFault == null)
            {
                return NotFound();
            }

            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Pending"), "StatusID", "StatusDesc");

            return View(fridgeFault);
        }

        [HttpPost]
        public async Task<IActionResult> RejectFault(int? id, FridgeFault fault)
        {
            var rejectStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Rejected").FirstOrDefaultAsync();

            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);

            if (fridgeFault == null)
            {
                return NotFound();
            }

            fridgeFault.StatusID = rejectStatus.StatusID;

            _context.Update(fridgeFault);
            await _context.SaveChangesAsync();

            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Rejected"), "StatusID", "StatusDesc");

            return RedirectToAction(nameof(ApproveFaultIndex));
        }

        [HttpGet]
        public async Task<IActionResult> ScheduleRepair(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fridgeFault = await _context.fridgeFaults
                .Include(f => f.faultType)
                .Include(f => f.status)
                .FirstOrDefaultAsync(m => m.FridgeFaultID == id);
            if (fridgeFault == null)
            {
                return NotFound();
            }

            ViewData["FaultTypeID"] = new SelectList(_context.faultTypes, "FaultTypeID", "FaultTypeDesc");
            ViewData["StatusID"] = new SelectList(_context.statuses
                .Where(y => y.StatusDesc == "Accepted"), "StatusID", "StatusDesc");

            return View(fridgeFault);
        }

        [HttpPost]
        public async Task<IActionResult> ScheduleRepair(int? id, FridgeFault fault)
        {
            var approveStatus = await _context.statuses
                .Where(y => y.StatusDesc == "Accepted").FirstOrDefaultAsync();

Cool Co Fridge Management/Views/FridgeFaults/AcceptedFaults.cshtml
@model IEnumerable<Cool_Co_Fridge_Management.Models.FridgeFault>

@{
    ViewData["Title"] = "Accepted Faults";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>ACCEPTED FRIDGE FAULTS</h1>
        </div>
    </div>
</div>
<hr/> 

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.faultType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReportedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.faultType.FaultTypeDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReportedOn)
                </td>
                <td style="color:springgreen">
                    @Html.DisplayFor(modelItem => item.status.StatusDesc)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.FridgeFaultID">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Cool Co Fridge Management/Views/FridgeFaults/ApproveFault.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Approve Fault";
}

<h1>Details</h1>

<form asp-action="ApproveFault" method="post">
    <div>
        <h4>FridgeFault</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.faultType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.faultType.FaultTypeDesc)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ReportedOn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ReportedOn)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.status.StatusDesc)
            </dd>
        </dl>
    </div>
    <div>
        <input type="submit" value="Approve" class="btn btn-primary" /> |
        <a class="btn btn-danger" asp-action="ApproveFaultIndex">Back to List</a>
    </div>
</form>

Cool Co Fridge Management/Views/FridgeFaults/BeyondRepairFridgeCondition.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Beyond Repair Condition Update";
}



<h1>Details</h1>

<form asp-action="BeyondRepairFridgeCondition" method="post">
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.faultType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.faultType.FaultTypeDesc)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ReportedOn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ReportedOn)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RepairDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RepairDate)
            </dd>
        </dl>
    </div>
    <div>
        <input type="submit" value="Update To Beyond Repair" class="btn btn-primary" /> |
        <a class="btn btn-danger" asp-action="FridgeConditionIndex">Back to List</a>
    </div>
</form>

Cool Co Fridge Management/Views/FridgeFaults/Create.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>CREATE FRIDGE FAULT</h1>
        </div>
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FaultTypeID" class="control-label"></label>
                <select asp-for="FaultTypeID" class ="form-control" asp-items="ViewBag.FaultTypeID"></select>
            </div>
            @* <div class="form-group">
                <label asp-for="ReportedOn" class="control-label"></label>
                <input asp-for="ReportedOn" class="form-control" />
                <span asp-validation-for="ReportedOn" class="text-danger"></span>
            </div> *@
            @* <div class="form-group">
                <label asp-for="StatusID" class="control-label"></label>
                <select asp-for="StatusID" class ="form-control" asp-items="ViewBag.StatusID"></select>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cool Co Fridge Management/Views/FridgeFaults/Details.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FridgeFault</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.faultType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.faultType.FaultTypeDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReportedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReportedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status.StatusDesc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FridgeFaultID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cool Co Fridge Management/Views/FridgeFaults/Edit.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FridgeFault</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FridgeFaultID" />
            <div class="form-group">
                <label asp-for="FaultTypeID" class="control-label"></label>
                <select asp-for="FaultTypeID" class="form-control" asp-items="ViewBag.FaultTypeID"></select>
                <span asp-validation-for="FaultTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReportedOn" class="control-label"></label>
                <input asp-for="ReportedOn" class="form-control" />
                <span asp-validation-for="ReportedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusID" class="control-label"></label>
                <select asp-for="StatusID" class="form-control" asp-items="ViewBag.StatusID"></select>
                <span asp-validation-for="StatusID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cool Co Fridge Management/Views/FridgeFaults/FaultTechIndex.cshtml
@model IEnumerable<Cool_Co_Fridge_Management.Models.FridgeFault>

<link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
<link href="~/faulttechnician/css/styles.css" rel="stylesheet" />
<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

<body class="sb-nav-fixed">
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Dashboard</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active"></li>
                </ol>
                <hr/>
                <div class="row">
                    <div class="col-xl-3 col-md-6">
                        <div class="card bg-primary text-white mb-4">
                            <div class="card-body">Fridge Condition</div>
                            <div class="card-footer d-flex align-items-center justify-content-between">
                                <a class="small text-white stretched-link" asp-area="" asp-controller="FridgeFaults" asp-action="FridgeConditionIndex">View Details</a>
                                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card bg-warning text-white mb-4">
                            <div class="card-body">Pending Faults</div>
                            <div class="card-footer d-flex align-items-center justify-content-between">
                                <a class="small text-white stretched-link" asp-area="" asp-controller="FridgeFaults" asp-action="ApproveFaultIndex">View Details</a>
                                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card bg-success text-white mb-4">
                            <div class="card-body">Accepted Faults</div>
                            <div class="card-footer d-flex align-items-center justify-content-between">
                                <a class="small text-white stretched-link" asp-area="" asp-controller="FridgeFaults" asp-action="AcceptedFaults">View Details</a>
                                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card bg-danger text-white mb-4">
                            <div class="card-body">Rejected Faults</div>
                            <div class="card-footer d-flex align-items-center justify-content-between">
                                <a class="small text-white stretched-link" asp-area="" asp-controller="FridgeFaults" asp-action="RejectedFaults">View Details</a>
                                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Repair Schedules
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.faultType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ReportedOn)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.status)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.RepairDate)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            @* <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Office</th>
                                    <th>Age</th>
                                    <th>Start date</th>
                                    <th>Salary</th>
                                </tr>
                            </tfoot> *@
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.faultType.FaultTypeDesc)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ReportedOn)
                                        </td>
                                        <td style="color:green">
                                            @Html.DisplayFor(modelItem => item.status.StatusDesc)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RepairDate)
                                        </td>
                                        <td>
                                            <a asp-action="ScheduleRepair" asp-route-id="@item.FridgeFaultID">Schedule Repair</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/faulttechnician/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/faulttechnician/js/datatables-simple-demo.js"></script>
</body>

Cool Co Fridge Management/Views/FridgeFaults/FixedFridgeCondition.cshtml
@model Cool_Co_Fridge_Management.Models.FridgeFault

@{
    ViewData["Title"] = "Fixed Condition Update";
}



<h1>Details</h1>

<form asp-action="FixedFridgeCondition" method="post">
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.faultType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.faultType.FaultTypeDesc)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ReportedOn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ReportedOn)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RepairDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RepairDate)
            </dd>
        </dl>
    </div>
    <div>
        <input type="submit" value="Update To Fixed" class="btn btn-primary" /> |
        <a class="btn btn-danger" asp-action="FridgeConditionIndex">Back to List</a>
    </div>
</form>



@* <div class="container">
    <form asp-action="FixedFridgeCondition">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row row-cols-2">
            <input type="hidden" asp-for="FridgeFaultID" />
            <div class="form-group">
                <label asp-for="FaultTypeID" class="control-label"></label>
                <select asp-for="FaultTypeID" class="form-control" asp-items="ViewBag.FaultTypeID" disabled></select>
                <span asp-validation-for="FaultTypeID" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="ReportedOn" class="control-label"></label>
                <input asp-for="ReportedOn" class="form-control" disabled />
                <span asp-validation-for="ReportedOn" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RepairDate" class="control-label"></label>
                <select asp-for="RepairDate" class="form-control" asp-items="ViewBag.RepairDate" disabled></select>
                <span asp-validation-for="RepairDate" class="text-danger"></span>
            </div>
            <br />
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Update Condition" class="btn btn-primary" />
            <a class="btn btn-danger" asp-action="Index">Back to List</a>
        </div>
    </form>
</div> *@

Cool Co Fridge Management/Views/FridgeFaults/FridgeConditionIndex.cshtml
@model IEnumerable<Cool_Co_Fridge_Management.Models.FridgeFault>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>FRIDGE CONDITION</h1>
        </div>
    </div>
</div>
<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.faultType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReportedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepairDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Condition)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.faultType.FaultTypeDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReportedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RepairDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Condition.ConditionDesc)
                </td>
                <td>
                    <a asp-action="FixedFridgeCondition" asp-route-id="@item.FridgeFaultID">Fixed</a> |
                    <a asp-action="BeyondRepairFridgeCondition" asp-route-id="@item.FridgeFaultID">Beyond Repair</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-action="FaultTechIndex">Back</a>
</p>