Cool Co Fridge Management/Models/PurchaseRequest.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cool_Co_Fridge_Management.Models
{
    public class PurchaseRequest
    {
        [Key]
        public int PurchaseRequestId { get; set; }
        [Required(ErrorMessage ="Fridge Type is required")]
        public int FridgeTypeID { get; set; }
        [Required(ErrorMessage = "Date is required")]
        public DateTime DateCreated { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than zero")]
        public int RequestQuantity { get; set; }
        [Required(ErrorMessage = "Status is required")]
        public int OrderStatusId { get; set; }
        public Fridge_Type? FridgeType { get; set; }
        public OrderStatus? OrderStatus { get; set; }
    }
}

Cool Co Fridge Management/Controllers/PurchaseRequestController.cs
using Cool_Co_Fridge_Management.Data;
using Microsoft.AspNetCore.Mvc;
using Cool_Co_Fridge_Management.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cool_Co_Fridge_Management.Attributes;

namespace Cool_Co_Fridge_Management.Controllers
{
    public class PurchaseRequestController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public PurchaseRequestController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Requests() //list of requests placed. Sil
        {
            var requests = _dbContext.PurchaseRequests.Include(p => p.FridgeType).Include(p => p.OrderStatus).ToList();
            if (!requests.Any())
            {
                TempData["Error Message"] = "No purchase requests found";
            }
            return View(requests);
        }
        //[RoleAuthorize("Stock Controller")]
        public IActionResult NewRequest() {
            var orderstatus = _dbContext.orderStatus.ToList();
            ViewBag.OrderStatus = new SelectList(orderstatus, "OrderStatusId", "OrderDesc");
            var type = _dbContext.fridge_type.ToList();
            ViewBag.Types = new SelectList(type, "FridgeTypeID", "FridgeType");

            var purchase = new PurchaseRequest
            {
                OrderStatusId = orderstatus.FirstOrDefault(p => p.OrderDesc == "Pending")?.OrderStatusId??2
            };
            return View(purchase);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewRequest(PurchaseRequest purchase)
        {
            if (!ModelState.IsValid)
            {
                // Debugging model state errors
                var errors = ModelState.Where(x => x.Value.Errors.Count > 0)
                                       .Select(x => new
                                       {
                                           Key = x.Key,
                                           Errors = x.Value.Errors.Select(e => e.ErrorMessage).ToList()
                                       })
                                       .ToList();
                foreach (var error in errors)
                {
                    Console.WriteLine($"Field: {error.Key}, Errors: {string.Join(", ", error.Errors)}");
                }
            }
            if (ModelState.IsValid)
            {
                _dbContext.Add(purchase);
                _dbContext.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Requests");
            }

            var orderstatus = _dbContext.orderStatus.ToList();
            ViewBag.OrderStatus = new SelectList(orderstatus, "OrderStatusId", "OrderDesc");
            var type = _dbContext.fridge_type.ToList();
            ViewBag.Types = new SelectList(type, "FridgeTypeID", "FridgeType");

            return View(purchase);
        }
        //[RoleAuthorize("Purchasing Manager")]
        public IActionResult UpdateRequest(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var request = _dbContext.PurchaseRequests.Include(p => p.FridgeType).FirstOrDefault(r => r.PurchaseRequestId == id);
            if(request == null)
            {
                return NotFound();
            }
            var orderstatus = _dbContext.orderStatus.ToList();
            ViewBag.OrderStatus = new SelectList(orderstatus, "OrderStatusId", "OrderDesc");

            return View(request);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateRequest(int id, PurchaseRequest request)
        {
            if (!ModelState.IsValid)
            {
                var orderstatus = _dbContext.orderStatus.ToList();
                ViewBag.OrderStatus = new SelectList(orderstatus, "OrderStatusId", "OrderDesc");
                return View(request);
            }

            if(request == null)
            {
                return NotFound();
            }

            _dbContext.Update(request);
            _dbContext.SaveChanges();
            //return RedirectToAction(nameof(Index));

            return View(request);
        }
        public IActionResult RequestDetails(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var request = _dbContext.PurchaseRequests.FirstOrDefault(m => m.PurchaseRequestId == id);
            if(request == null)
            {
                return NotFound();
            }
            return View(request);
        }


    }
}

Cool Co Fridge Management/Views/PurchaseRequest/NewRequest.cshtml
@model Cool_Co_Fridge_Management.Models.PurchaseRequest
<h1>New Request</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action=NewRequest>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FridgeTypeID" class="control-label"></label>
                <select asp-for="FridgeTypeID" class="form-control" asp-items="ViewBag.Types">
                    <option value="">Select Fridge Type</option>
                </select>
                <span asp-validation-for="FridgeTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" type="datetime-local" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestQuantity" class="control-label"></label>
                <input asp-for="RequestQuantity" class="form-control" />
                <span asp-validation-for="RequestQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderStatusId" class="control-label"></label>
                <select asp-for="OrderStatusId" class="form-control" asp-items="ViewBag.OrderStatus"></select>
                <span asp-validation-for="OrderStatusId" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Send Request" class="btn btn-primary" name="submit" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Requests">Back</a>
</div>

Cool Co Fridge Management/Views/PurchaseRequest/Requests.cshtml
@model IEnumerable<Cool_Co_Fridge_Management.Models.PurchaseRequest>
@{
    ViewData["Title"] = "Purchase Requests";
}
<h1>Purchase Requests</h1>
<p>
    <a asp-action="NewRequest">New Request</a>
</p>
<p>
    <a asp-controller="RFQViewModels" asp-action="Index">RFQ</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Purchase Request #</th>
            <th>Fridge Type</th>
            <th>Date Created</th>
            <th>Quantity</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var requests in Model){
            <tr>
                <td>@requests.PurchaseRequestId</td>
                <td>@requests.FridgeType?.FridgeType</td>
                <td>@requests.DateCreated</td>
                <td>@requests.RequestQuantity</td>
                <td>@requests.OrderStatus?.OrderDesc</td>
                <td>
                    <a asp-action="UpdateRequest" asp-route-id="@requests.PurchaseRequestId">Edit</a>
                </td>
                @* <td>
                    <a asp-action="RequestDetails" asp-route-id="@requests.PurchaseRequestId">Details</a>
                </td> *@

            </tr>
        }
    </tbody>
</table>

Cool Co Fridge Management/Views/PurchaseRequest/UpdateRequest.cshtml
@model Cool_Co_Fridge_Management.Models.PurchaseRequest
@{
    ViewData["Title"] = "Update Purchase Request";
}
<h1>Update Purchase Request</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="UpdateRequest">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PurchaseRequestId" class="control-label"></label>
                <input asp-for="PurchaseRequestId" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="FridgeType.FridgeType" class="control-label"></label>
                <input asp-for="FridgeType.FridgeType" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="RequestQuantity" class="control-label"></label>
                <input asp-for="RequestQuantity" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="OrderStatusId" class="control-label"></label>
                <select asp-for="OrderStatus" class="form-control" asp-items="ViewBag.OrderStatus">
                    <option value="">--Status--</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Approve" class="btn btn-primary" />
            </div>
            <a asp-controller="PurchaseRequest" asp-action="Requests" class="btn">Back<</a>
        </form>
    </div>
</div>